import './globals.css'
import { Inter, Roboto_Mono, Poppins } from 'next/font/google'
import { AuthProvider } from './components/store'

const inter = Inter({ subsets: ['latin'] })
const popins = Poppins({
  subsets: ['devanagari'],
  variable: '--font-popins',
  weight: '300'
})
const PopinsLarge = Poppins({
  subsets: ['devanagari'],
  variable: '--font-popinsLarge',
  weight: '400'
})
const roboto_mono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto-mono',
})

export const metadata = {
  title: 'Login App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${roboto_mono.variable} ${popins.variable} ${PopinsLarge.variable}`}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
